app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('user/{user}', [
    'middleware' => ['auth', 'roles'], // A 'roles' middleware must be specified
    'uses' => 'UserController@index',
    'roles' => ['administrator', 'manager'] // Only an administrator, or a manager can access this route
]);

/* USER LOGIN AND REGISTRATION*/
Route::get('/', function () {
    return redirect('auth/login');
});

Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::group(['prefix' => 'register/'], function () {
    Route::get('verify/{confirmationCode}',	[
    	'as'	=> 'confirmation_path',
    	'uses'	=> 'RegistrationController@confirm'
    ]);
    
    Route::get('activate/{confirmationCode}', [
    	'as'	=> 'activation_path',
    	'uses'	=> 'RegistrationController@activate'
    ]);

    Route::get('sendconfirmation', function() {
        return view('email.sendconfirmation');
    });

    Route::get('sendpassword', function() {
        return redirect('auth/login');
    });

});
/* END - USER LOGIN AND REGISTRATION*/

/* MANAGE USER */
// TODO:: homepage
Route::get('/home', function () {
    return redirect('userlists');
});

// Route::group(function () {
    Route::get('dashboard', [
        'as'    => 'user_dashboard',
        'uses'  => 'UserController@dashboard'
    ]);

Route::get('userlists', [
    'as'    => 'user_lists',
    // 'middleware' => 'admin',
    'uses'  => 'UserController@lists'
]);
Route::post('userupdate', [
    'as'    => 'user_update',
    'uses'  => 'UserController@update'
]);

    Route::get('roles', [
        'as'    => 'user_roles',
        'uses'  => 'UserController@roles'
    ]);
    Route::get('permissions', [
        'as'    => 'user_permissions',
        'uses'  => 'UserController@permissions'
    ]);
// });
/* END - MANAGE USER */

use App\Message;
use App\User;
get('userlist', function() {
    return view('user.lists');
});
/*API*/
get('api/users', function() {
    return User::all();
});

post('api/users', function() {
    return Message::create(Request::all());
});
/*END - API*/


get('guestbook', function() {
    return view('guestbook');
});

// API

get('api/messages', function() {
    return Message::all();
});

post('api/messages', function() {
    return Message::create(Request::all());
});

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $fillable = [
        'name', 'message'
    ];
}

app/Role.php
<?php 

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model {

    protected $table = 'roles';

    public function users()
    {
        return $this->hasMany('App\User', 'role_id', 'id');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Carbon\CarbonInterval;
use Carbon\Carbon;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['first_name', 'last_name', 'middle_name', 'email', 'confirmation_code', 'password'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function getCreatedAtAttribute($value)
    {
        $cdate = CarbonInterval::days((new Carbon($value))->diff(Carbon::now())->days);
        return ($cdate == '')? 'Today' : $cdate.' ago';
    }

    public function getUpdatedAtAttribute($value)
    {
        $udate = CarbonInterval::days((new Carbon($value))->diff(Carbon::now())->days);
        return ($udate == '')? 'Today' : $udate.' ago';
    }

    /*User Model*/
    public function role()
    {
        return $this->hasOne('App\Role', 'id', 'role_id');
    }
    public function hasRole($roles)
    {
        $this->have_role = $this->getUserRole();
        // Check if the user is a root account
        if($this->have_role->name == 'Root') {
            return true;
        }
        if(is_array($roles)){
            foreach($roles as $need_role){
                if($this->checkIfUserHasRole($need_role)) {
                    return true;
                }
            }
        } else{
            return $this->checkIfUserHasRole($roles);
        }
        return false;
    }
    private function getUserRole()
    {
        return $this->role()->getResults();
    }
    private function checkIfUserHasRole($need_role)
    {
        return (strtolower($need_role)==strtolower($this->have_role->name)) ? true : false;
    }
    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/RegistrationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\User;

class RegistrationController extends Controller
{
    public function confirm($confirmation_code)
    {

        if( ! $confirmation_code)
        {
            return view('email.expiredConfirmation');
            // throw new InvalidConfirmationCodeException;
        }

        $user = User::whereConfirmationCode($confirmation_code)->first();
        if ( ! $user)
        {
            return view('email.expiredConfirmation');
            // throw new InvalidConfirmationCodeException;
        }

        $user->confirmed = 1;
        $user->save();
        if($user->active == 0){
            return view('email.confirmation');
        }else{
            $user->confirmation_code = null;
            $user->save();
            return redirect('auth/login');
        }

    }

    public function activate($confirmation_code)
    {

        if( ! $confirmation_code)
        {
            throw new InvalidConfirmationCodeException;
        }

        $user = User::whereConfirmationCode($confirmation_code)->first();

        if ( ! $user)
        {
            throw new InvalidConfirmationCodeException;
        }

        $user->active = 1;
        $user->save();

    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;
use App\User;

class UserController extends Controller
{
    public function dashboard(){
    	return view('user.dashboard');
    }

    public function lists(){
    	$users = User::all();
    	return view('user.lists', compact('users'));
    }

    public function update(Request $request){
        $user = User::where('email', $request->email)->first();
        $user->first_name   = $request->first_name;
        $user->middle_name  = $request->middle_name;
        $user->last_name    = $request->last_name;
        $user->confirmed    = $request->has('confirmed')? 1 : 0;
        $user->active       = $request->has('active')? 1 : 0;
        $user->save();
        return redirect('userlists');
    }

    public function roles(){
    	return view('user.dashboard');
    }

    public function permissions(){
    	$user = Auth::user();
    	return view('user.dashboard');
    }
}

resources/views/layouts/master/front.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>App Name | @yield('title')</title>
    <link rel="shortcut icon" type="image/png" href="{{ asset('../public/favicon.ico') }}"/>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link href="{{ asset('../vendor/almasaeed2010/adminlte/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('../vendor/fortawesome/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('../vendor/driftyco/ionicons/css/ionicons.min.css') }}" rel="stylesheet">
    <link href="{{ asset('../vendor/almasaeed2010/adminlte/dist/css/AdminLTE.min.css') }}" rel="stylesheet">
    <link href="{{ asset('../vendor/almasaeed2010/adminlte/plugins/iCheck/square/blue.css') }}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="hold-transition login-page">
    @yield('content')
    @stack('scripts')
  </body>
</html>

resources/views/layouts/master/user/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{ asset('/default_user.png') }}" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>{!! Auth::user()->first_name.' '.Auth::user()->last_name !!}</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->
  <!--====================================================================================-->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
    <li class="header">MAIN NAVIGATION</li>
      <li class="treeview">
        <a href="{{ route('user_dashboard') }}">
          <i class="fa fa-key"></i> <span>Access Management</span> <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="userlists"><i class="fa fa-users"></i> Users</a></li>
          <li><a href="{{ route('user_roles') }}"><i class="fa fa-gears"></i> Roles</a></li>
          <li><a href="{{ route('user_permissions') }}"><i class="fa fa-unlock-alt"></i> Permissions</a></li>
        </ul>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
  <!--====================================================================================-->
</aside>

resources/views/user/dashboard.blade.php
@extends('layouts.master.user.main')
@section('title', 'Login')

@section('section')
<section class="content-header">
          <h1>
            Blank page
            <small>it all starts here</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
          </ol>
</section>
@endsection

@section('content')

@endsection

resources/views/user/lists.blade.php
@extends('layouts.master.user.main')
@section('title', 'Users List')
@section('page_title', 'User Management')
@section('page_subtitle', '')
@section('content')
<link href="{{ asset('../vendor/almasaeed2010/adminlte/plugins/iCheck/all.css') }}" rel="stylesheet">
<link href="{{ asset('../vendor/almasaeed2010/adminlte/plugins/select2/select2.min.css') }}" rel="stylesheet">
<style>
#example1 tr {
    cursor: pointer;
}
#example1 tbody tr.highlight td {
    background-color: #9DD5F5;
}
#example1 tbody tr:hover{
    background-color: #9DD5F5 !important; 
}
</style>
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
                <div class="box-header">
                  <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <table id="example1" class="table table-bordered table-striped">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Roles</th>
                        <th>Created</th>
                        <th>Updated</th>
                        <th>Confirmed</th>
                        <th>Active</th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                      <tr id="{{ $user->id }}" data-target="#myModal_{{ $user->id }}" data-toggle="modal" data-tooltip="{!! $user->first_name !!}" style="width: 41px; height:34px;" data_value="{{ $user->id }}">
                        <td>{!! ucfirst($user->last_name.', '.$user->first_name.' '.$user->middle_name[0]) !!}.</td>
                        <td>{!! strtolower($user->email) !!}</td>
                        <td>{!! ($user->admin == 1)? 'Admin' : 'User' !!}</td>
                        <td>{!! $user->created_at !!}</td>
                        <td>{!! $user->updated_at !!}</td>
                        <td>{!! ($user->confirmed == 1)? '<span class="bg-green btn-xs">Yes</span>' : '<span class="bg-yellow btn-xs">No</span>' !!}</td>
                        <td>{!! ($user->active == 1)? '<span class="bg-green btn-xs">Yes</span>' : '<span class="bg-yellow btn-xs">No</span>' !!}</td>
                        @include('user.modal')
                      </tr>
                    @endforeach
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </section><!-- /.content -->
        
@endsection
@push('jscripts')
<!-- DataTables -->

  <script src="{{ asset('../vendor/almasaeed2010/adminlte/plugins/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('../vendor/almasaeed2010/adminlte/plugins/datatables/dataTables.bootstrap.min.js') }}"></script>
  <script src="{{ asset('../vendor/almasaeed2010/adminlte/plugins/select2/select2.full.min.js') }}"></script>
  <script src="{{ asset('../vendor/almasaeed2010/adminlte/plugins/input-mask/jquery.inputmask.js') }}"></script>
  <script src="{{ asset('../vendor/almasaeed2010/adminlte/plugins/daterangepicker/daterangepicker.js') }}"></script>
  <script src="{{ asset('../vendor/almasaeed2010/adminlte/plugins/iCheck/icheck.min.js') }}"></script>
  <script src="{{ asset('/js/moment.js') }}"></script>

  <script>
    $(function () {
      $("#example1").DataTable();
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
      });
    });
    $('#example1').on('click', 'tbody tr', function(event) {
      $(this).addClass('highlight').siblings().removeClass('highlight');
      var trid = $(this).attr('id');
      console.log(trid);
      // $('#myModal').modal('show');
    });
    $(function () {
        //Initialize Select2 Elements
        $(".select2").select2();

        //Flat red color scheme for iCheck
        $('input[type="checkbox"].flat-red, input[type="radio"].flat-red').iCheck({
          checkboxClass: 'icheckbox_flat-green',

        });

      });
  </script>
@endpush

resources/views/user/modal.blade.php
<!-- Modal -->
<div class="modal fade" id="myModal_{{ $user->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Update User</h4>
      </div>
      <div class="modal-body">
      {!! Form::model($user, ['route' => ['user_update', $user->id]]) !!}
          {!! Form::token() !!}
            <div class="form-group has-feedback {{ $errors->has('first_name') ? 'has-error' : '' }}">
              {!! Form::text('first_name', $user->first_name, ['class'=>'form-control', 'placeholder'=>'First name', 'required' => 'required']) !!}
              <span class="glyphicon glyphicon-user form-control-feedback"></span>
              @if ($errors->has('first_name')) <p class="help-block">{{ $errors->first('first_name') }}</p> @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('middle_name') ? 'has-error' : '' }}">
              {!! Form::text('middle_name', $user->middle_name, ['class'=>'form-control', 'placeholder'=>'Middle name', 'required' => 'required']) !!}
              <span class="glyphicon glyphicon-user form-control-feedback"></span>
              @if ($errors->has('middle_name')) <p class="help-block">{{ $errors->first('middle_name') }}</p> @endif
            </div>
            <div class="form-group has-feedback {{ $errors->has('last_name') ? 'has-error' : '' }}">
              {!! Form::text('last_name', $user->last_name, ['class'=>'form-control', 'placeholder'=>'Last name', 'required' => 'required']) !!}
              <span class="glyphicon glyphicon-user form-control-feedback"></span>
              @if ($errors->has('last_name')) <p class="help-block">{{ $errors->first('last_name') }}</p> @endif
            </div>
            <div class="form-group has-feedback">
              {!! Form::email('email', $user->email, ['class'=>'form-control', 'placeholder'=>'Email', 'readonly' => 'true']) !!}
              <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>
            <div class="form-group">
              {!! Form::checkbox('confirmed', $user->confirmed, ($user->confirmed==1) ? true: false) !!}
              &nbsp;&nbsp;Confirmed
              &nbsp;&nbsp;
              {!! Form::checkbox('active', $user->active, ($user->active==1) ? true: false) !!}
              &nbsp;&nbsp;Active
            </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          {!! Form::submit('Save changes', ['class'=>'btn btn-primary']) !!}
        </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>
<script src="{{ asset('../vendor/almasaeed2010/adminlte/plugins/iCheck/icheck.min.js') }}"></script>